In [1]:
import os
os.environ["JAX_PLATFORM_NAME"] = "cpu"

import jax

%matplotlib inline
import jax.numpy as jnp
import jax
import numpy as onp
from jax import random

In [20]:
sigma_2 = 1 
ell = 1 

x = jnp.array([-1, 0, 1]) # shape (n,)

# reshape to a column vector (cv) # shape(n, 1)
x_cv = jnp.array([-1, 0, 1]).reshape(-1, 1)
print(f"Shape of x_r is: {x_cv.shape}")

# reshape x to a row vector (rw) # shape (1, n)
x_rv = x.reshape(1, -1) 
print(f"Shape of x_r is: {x_rv.shape}")


# build (n, n) matrix by calculating the distance 
X = x_cv - x_rv
print(X)

X_2 = (x_cv - x_rv)**2
print(X_2)

exp_formula = jnp.exp(- X_2/ (2*ell**2))
print(exp_formula)

Shape of x_r is: (3, 1)
Shape of x_r is: (1, 3)
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
[[0 1 4]
 [1 0 1]
 [4 1 0]]
[[1.         0.60653067 0.13533528]
 [0.60653067 1.         0.60653067]
 [0.13533528 0.60653067 1.        ]]


In [21]:
sigma_2 = 1 
ell = 1 

def squared_exponential_kernel(x, ell=1, sigma2=1.0):
    """
    Compute the squared exponential (RBF) kernel matrix.
    
    This kernel computes:
        K_ij = sigma2 * exp( - (x_i - x_j)^2 / (2 * ell^2) )
        
    Args:
        x (jnp.ndarray): 1D array of input points, shape (n,)
        ell (float): Length-scale parameter. Controls smoothness. Default is 1.0.
        sigma2 (float): Output variance. Scales the kernel. Default is 1.0.
        
    Returns:
        jnp.ndarray: Squared exponential kernel matrix of shape (n, n)
        
    Example:
        >>> import jax.numpy as jnp
        >>> x = jnp.array([-1.0, 0.0, 1.0])
        >>> K = squared_exponential_kernel(x)
        >>> print(K)
        [[1.         0.60653067 0.13533528]
        [0.60653067 1.         0.60653067]
        [0.13533528 0.60653067 1.        ]]
    """
    
    # reshape x into column and row vectors 
    x_col = x.reshape(-1, 1)    # shape (n, 1)
    x_row = x.reshape(1, -1)    # shape (1, n)
    
    # compute squared pairwise distances 
    sq_dist = (x_col - x_row) ** 2  # shape (n, n)
    
    # compute kernel matrix 
    K = sigma2 * jnp.exp(-sq_dist / (2 * ell ** 2)) # shape (n, n)
    
    return K 

In [22]:
print(squared_exponential_kernel(x))

[[1.         0.60653067 0.13533528]
 [0.60653067 1.         0.60653067]
 [0.13533528 0.60653067 1.        ]]


In [29]:
x_col = 0.5
x_row = -1
sigma2 = 1 
ell = 1

sq_dist = (x_col - x_row) ** 2  # shape (n, n)
    
    # compute kernel matrix 
K = sigma2 * jnp.exp(-sq_dist / (2 * ell ** 2)) # shape (n, n)
print(K)

0.32465246
