In [3]:
import jax.numpy as jnp

In [5]:
samples1 = jnp.arange(3001*2).reshape(3001, 2)
samples2 = jnp.arange(3001*2, 3001*4).reshape(3001, 2)

In [6]:
print(f"Samples 1 shape = {samples1.shape}")
print(f"Samples 2 shape = {samples2.shape}")

Samples 1 shape = (3001, 2)
Samples 2 shape = (3001, 2)


In [9]:
samples = jnp.concatenate([samples1, samples2])

print(samples.shape)

(6002, 2)


In [14]:
z, x = samples.T 


print(print(z.shape))

(6002,)
None


In [13]:
print(samples)

[[    0     1]
 [    2     3]
 [    4     5]
 ...
 [11998 11999]
 [12000 12001]
 [12002 12003]]


In [15]:
z1 = samples[:, 0]

x1 = samples[:, 1]

In [17]:
print(z1)
print(z)

[    0     2     4 ... 11998 12000 12002]
[    0     2     4 ... 11998 12000 12002]


#### Exercise 2: Extracting Columns with Slicing and Transposing

**Task:**
Given a single 2D array A of shape (5, 3):

In [18]:
A = jnp.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33],
    [41, 42, 43],
    [51, 52, 53]
])

In [23]:
col2 = A[:, 1]

In [24]:
print(col2)

[12 22 32 42 52]


In [28]:
A_T = A.T 
print(A_T.shape)

(3, 5)


In [30]:
print(A_T)

[[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]]


In [34]:
r1 = A_T[0, :]
r2 = A_T[1, :]
r3 = A_T[2, :]

In [35]:
print(r1.shape)

(5,)
